server:
  port: 5566
spring:
  application:
    name: active
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1785978e4noor70yo.mysql.rds.aliyuncs.com/ans_crm?useSSL=false&allowMultiQueries=true
    username: root
    password: Ans12345
    tomcat:
      initial-size: 5
      min-idle: 2
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: false
      testOnBorrow: false
      testOnReturn: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 1000
        max-wait: -1
        min-idle: 50
    timeout: 3000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.crm.active.entity
  configuration:
    call-setters-on-nulls: true