server:
  port: 5566
spring:
  application:
    name: active
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.30.10:3306/ans_crm?useSSL=false&allowMultiQueries=true
    username: root
    password: ho4gaI81
    tomcat:
      initial-size: 5
      min-idle: 2
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: false
      testOnBorrow: false
      testOnReturn: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: 192.168.30.157
    port: 6379
    jedis:
      pool:
        max-idle: 1000
        max-wait: -1
        min-idle: 50
    timeout: 3000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.crm.active.entity
  configuration:
    call-setters-on-nulls: true